### ISSUE TITLE
Webhook not working

### ISSUE THREAD

**Issue by sasogeek** [Flutterwave/rave-react-native#19]
I've setup a webhook but it doesn't get called after a transaction has initiated. Transaction reflects on the dashboard but the webhook never executes. Why does that happen?

**Comment by MaestroJolly** [comment]
Hi @sasogeek , please confirm if you are implementing this on your rave sandbox account (https://ravesandbox.flutterwave.com) or your live account (https://rave.flutterwave.com)?

**Comment by temiadesina** [comment]
Hi @sasogeek it's been 14days since your last reply, we would be closing this issue, please feel free to open it again if you are still experiencing the issue.

If you open the issue again, please be sure to provide the following

1. The environment you are working on i.e. test or live
2. Your hook URL

Thanks
